// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpSkillDashboard.Data;

#nullable disable

namespace UpSkillDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429003954_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UpSkillDashboard.Models.Advertisement", b =>
                {
                    b.Property<int>("AdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertisementId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("AdvertisementId");

                    b.HasIndex(new[] { "SponsorId" }, "IX_Advertisements_SponsorId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.ApplicationStatus", b =>
                {
                    b.Property<int>("ApplicationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationStatusId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ApplicationStatusId");

                    b.ToTable("ApplicationStatuses");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackNationalIdPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontNationalIdPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex(new[] { "NationalId" }, "IX_Clients_NationalId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_Clients_UserId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.ClientPost", b =>
                {
                    b.Property<int>("ClientPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientPostId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2550)
                        .HasColumnType("nvarchar(2550)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostStatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientPostId");

                    b.HasIndex(new[] { "ClientId" }, "IX_ClientPosts_ClientId");

                    b.HasIndex(new[] { "PostStatusId" }, "IX_ClientPosts_PostStatusId");

                    b.HasIndex(new[] { "ProfessionId" }, "IX_ClientPosts_ProfessionId");

                    b.ToTable("ClientPosts");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentationPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrganizationId");

                    b.HasIndex(new[] { "UserId" }, "IX_Organizations_UserId")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.PostStatus", b =>
                {
                    b.Property<int>("PostStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostStatusId");

                    b.ToTable("PostStatuses");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Profession", b =>
                {
                    b.Property<int>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfessionId");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex(new[] { "ClientId" }, "IX_Ratings_ClientId");

                    b.HasIndex(new[] { "WorkerId" }, "IX_Ratings_WorkerId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Sponsor", b =>
                {
                    b.Property<int>("SponsorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SponsorId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SponsorId");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValueSql("(0x)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValueSql("(0x)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.VolunteeringApplication", b =>
                {
                    b.Property<int>("VolunteeringApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteeringApplicationId"));

                    b.Property<int>("ApplicantType")
                        .HasColumnType("int");

                    b.Property<int>("ApplicantTypeEnum")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VolunteeringJobId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("VolunteeringApplicationId");

                    b.HasIndex(new[] { "ApplicationStatusId" }, "IX_VolunteeringApplications_ApplicationStatusId");

                    b.HasIndex(new[] { "ClientId" }, "IX_VolunteeringApplications_ClientId");

                    b.HasIndex(new[] { "VolunteeringJobId" }, "IX_VolunteeringApplications_VolunteeringJobId");

                    b.HasIndex(new[] { "WorkerId" }, "IX_VolunteeringApplications_WorkerId");

                    b.ToTable("VolunteeringApplications");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.VolunteeringJob", b =>
                {
                    b.Property<int>("VolunteeringJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteeringJobId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberOfPeopleNeeded")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PostStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VolunteeringJobId");

                    b.HasIndex(new[] { "OrganizationId" }, "IX_VolunteeringJobs_OrganizationId");

                    b.HasIndex(new[] { "PostStatusId" }, "IX_VolunteeringJobs_PostStatusId");

                    b.ToTable("VolunteeringJobs");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackNationalIdPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClearanceCertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FrontNationalIdPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WorkerId");

                    b.HasIndex(new[] { "NationalId" }, "IX_Workers_NationalId")
                        .IsUnique();

                    b.HasIndex(new[] { "ProfessionId" }, "IX_Workers_ProfessionId");

                    b.HasIndex(new[] { "UserId" }, "IX_Workers_UserId")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.WorkerApplication", b =>
                {
                    b.Property<int>("WorkerApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerApplicationId"));

                    b.Property<int>("ApplicationStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClientPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("WorkerApplicationId");

                    b.HasIndex(new[] { "ApplicationStatusId" }, "IX_WorkerApplications_ApplicationStatusId");

                    b.HasIndex(new[] { "ClientPostId" }, "IX_WorkerApplications_ClientPostId");

                    b.HasIndex(new[] { "WorkerId" }, "IX_WorkerApplications_WorkerId");

                    b.ToTable("WorkerApplications");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Advertisement", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.Sponsor", "Sponsor")
                        .WithMany("Advertisements")
                        .HasForeignKey("SponsorId")
                        .IsRequired();

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Client", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("UpSkillDashboard.Models.Client", "UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.ClientPost", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.Client", "Client")
                        .WithMany("ClientPosts")
                        .HasForeignKey("ClientId")
                        .IsRequired();

                    b.HasOne("UpSkillDashboard.Models.PostStatus", "PostStatus")
                        .WithMany("ClientPosts")
                        .HasForeignKey("PostStatusId")
                        .IsRequired();

                    b.HasOne("UpSkillDashboard.Models.Profession", "Profession")
                        .WithMany("ClientPosts")
                        .HasForeignKey("ProfessionId")
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PostStatus");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Organization", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.User", "User")
                        .WithOne("Organization")
                        .HasForeignKey("UpSkillDashboard.Models.Organization", "UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Rating", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.Client", "Client")
                        .WithMany("Ratings")
                        .HasForeignKey("ClientId")
                        .IsRequired();

                    b.HasOne("UpSkillDashboard.Models.Worker", "Worker")
                        .WithMany("Ratings")
                        .HasForeignKey("WorkerId")
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.VolunteeringApplication", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.ApplicationStatus", "ApplicationStatus")
                        .WithMany("VolunteeringApplications")
                        .HasForeignKey("ApplicationStatusId")
                        .IsRequired();

                    b.HasOne("UpSkillDashboard.Models.Client", "Client")
                        .WithMany("VolunteeringApplications")
                        .HasForeignKey("ClientId");

                    b.HasOne("UpSkillDashboard.Models.VolunteeringJob", "VolunteeringJob")
                        .WithMany("VolunteeringApplications")
                        .HasForeignKey("VolunteeringJobId")
                        .IsRequired();

                    b.HasOne("UpSkillDashboard.Models.Worker", "Worker")
                        .WithMany("VolunteeringApplications")
                        .HasForeignKey("WorkerId");

                    b.Navigation("ApplicationStatus");

                    b.Navigation("Client");

                    b.Navigation("VolunteeringJob");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.VolunteeringJob", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.Organization", "Organization")
                        .WithMany("VolunteeringJobs")
                        .HasForeignKey("OrganizationId")
                        .IsRequired();

                    b.HasOne("UpSkillDashboard.Models.PostStatus", "PostStatus")
                        .WithMany("VolunteeringJobs")
                        .HasForeignKey("PostStatusId")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("PostStatus");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Worker", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.Profession", "Profession")
                        .WithMany("Workers")
                        .HasForeignKey("ProfessionId")
                        .IsRequired();

                    b.HasOne("UpSkillDashboard.Models.User", "User")
                        .WithOne("Worker")
                        .HasForeignKey("UpSkillDashboard.Models.Worker", "UserId")
                        .IsRequired();

                    b.Navigation("Profession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.WorkerApplication", b =>
                {
                    b.HasOne("UpSkillDashboard.Models.ApplicationStatus", "ApplicationStatus")
                        .WithMany("WorkerApplications")
                        .HasForeignKey("ApplicationStatusId")
                        .IsRequired();

                    b.HasOne("UpSkillDashboard.Models.ClientPost", "ClientPost")
                        .WithMany("WorkerApplications")
                        .HasForeignKey("ClientPostId");

                    b.HasOne("UpSkillDashboard.Models.Worker", "Worker")
                        .WithMany("WorkerApplications")
                        .HasForeignKey("WorkerId")
                        .IsRequired();

                    b.Navigation("ApplicationStatus");

                    b.Navigation("ClientPost");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.ApplicationStatus", b =>
                {
                    b.Navigation("VolunteeringApplications");

                    b.Navigation("WorkerApplications");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Client", b =>
                {
                    b.Navigation("ClientPosts");

                    b.Navigation("Ratings");

                    b.Navigation("VolunteeringApplications");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.ClientPost", b =>
                {
                    b.Navigation("WorkerApplications");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Organization", b =>
                {
                    b.Navigation("VolunteeringJobs");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.PostStatus", b =>
                {
                    b.Navigation("ClientPosts");

                    b.Navigation("VolunteeringJobs");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Profession", b =>
                {
                    b.Navigation("ClientPosts");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Sponsor", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.User", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Organization");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.VolunteeringJob", b =>
                {
                    b.Navigation("VolunteeringApplications");
                });

            modelBuilder.Entity("UpSkillDashboard.Models.Worker", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("VolunteeringApplications");

                    b.Navigation("WorkerApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
